/*
 * MyCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 12/02/2016
 */
package io.apimatic.examples.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import io.apimatic.examples.models.*;
import io.apimatic.examples.exceptions.*;
import io.apimatic.examples.APIHelper;
import io.apimatic.examples.Configuration;
import io.apimatic.examples.testing.TestHelper;
import io.apimatic.examples.controllers.OperationController;

import com.fasterxml.jackson.core.type.TypeReference;

public class OperationControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static OperationController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getOperation();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Calculates the expression using the specified operation.
     * @throws Throwable
     */
    @Test
    public void testCalculate1() throws Throwable {
        // Parameters for the API call
        OperationEnum operation = OperationEnum.fromString("SUM");
        double x = 3.0d;
        double y = 8.0d;

        // Set callback and perform API call
        DynamicResponse result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getCalculate(operation, x, y);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "11.0", 
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

}
