/*
 * MyCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/02/2016
 */
package com.mulesoft.mocksvc;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://mocksvc.mulesoft.com/mocks/788ad2c8-18ce-454a-a7f3-b38c92484ff1/apps/calculator";

}
