/*
 * MyCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/02/2016
 */
package com.mulesoft.mocksvc;

import com.mulesoft.mocksvc.controllers.*;
import com.mulesoft.mocksvc.http.client.HttpClient;

public class MyCalculatorClient {
    /**
     * Singleton access to Operation controller
     * @return	Returns the OperationController instance 
     */
    public OperationController getOperation() {
        return OperationController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public MyCalculatorClient() {	
	}

}